In [22]:
import numpy as np

training_set = np.load('./training_set.npy')
no_training_set = training_set.shape[0]
print(no_training_set)
training_set

14


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 1],
       [2, 1, 0, 0, 1],
       [2, 2, 1, 0, 1],
       [2, 2, 1, 1, 0],
       [1, 2, 1, 1, 1],
       [0, 1, 0, 0, 0],
       [0, 2, 1, 0, 1],
       [2, 1, 1, 0, 1],
       [0, 1, 1, 1, 1],
       [1, 1, 0, 1, 1],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]])

In [27]:
class_no = training_set[training_set[:,-1]==0]
count_no = class_no.shape[0]
p_no = count_no/no_training_set #probability of no's
print(f'count_no : {count_no} probability : {p_no}')
class_no

count_no : 5 probability : 0.35714285714285715


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [2, 2, 1, 1, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 1, 0]])

In [28]:
class_yes = training_set[training_set[:,-1]==1]
count_yes = class_yes.shape[0]
p_yes = count_yes/no_training_set #probability of yes's
print(f'count_yes : {count_yes} probability : {p_yes}')
class_yes

count_yes : 9 probability : 0.6428571428571429


array([[1, 0, 0, 0, 1],
       [2, 1, 0, 0, 1],
       [2, 2, 1, 0, 1],
       [1, 2, 1, 1, 1],
       [0, 2, 1, 0, 1],
       [2, 1, 1, 0, 1],
       [0, 1, 1, 1, 1],
       [1, 1, 0, 1, 1],
       [1, 0, 1, 0, 1]])

In [48]:
#predicting for this input
input_feature = [0,0,0,1]

In [49]:
# probability for no
pred_prob_no = 1
for i in range(0,len(input_feature)): 
    count = 0
    for j in range(0,count_no):#iterating over each training example
        if(class_no[j,i]==input_feature[i]):
            count+=1
    if(count==0):
        count = 0.001
    
    pred_prob_no *= count/count_no #conditional probability wrt to each value

pred_prob_no

0.15360000000000004

In [50]:
pred_prob_yes = 1
for i in range(0,len(input_feature)):
    count = 0
    for j in range(0,count_yes):
        if(class_yes[j,i]==input_feature[i]):
            count+=1
    if(count==0):
        count = 0.0001
    
    pred_prob_yes *= count/count_yes

pred_prob_yes

0.005486968449931412

In [51]:
if(pred_prob_no>pred_prob_yes):
    print('No')
else:
    print('Yes')

No
